Array ( [0] => Array ( [id] => 7 [column_id] => 1 [table_id] => 33 [width] => 50 ) 
[1] => Array ( [id] => 8 [column_id] => 1 [table_id] => 33 [width] => 50 ) 
[2] => Array ( [id] => 9 [column_id] => 3 [table_id] => 33 [width] => 60 ) 
[3] => Array ( [id] => 10 [column_id] => 3 [table_id] => 33 [width] => 40 ) )	


                                                 if($table_width[$sub]['column_id']==$i){
                                                    ?>
                                                    ech
                                                      <?php
                                                 }